# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yKUZURRRiOlBEyO3khqKyzZYehbG0RAm

```markdown
# Streamlit Violence Detection App

To run this Streamlit application in Google Colab, you need to follow these steps:

1.  **Install Streamlit:** Run `!pip install streamlit` in a code cell.
2.  **Save the app code:** The code below defines your Streamlit application.
3.  **Run the app:** Use `!streamlit run your_app_name.py & npx localtunnel --port 8501` in a code cell to run the app and expose it via a public URL. You will see a link to access your app in the output.

Since Colab notebooks automatically save as `.ipynb` files, a common practice is to write the Streamlit app code to a `.py` file first, then run that file. I will place the code in a cell for now, and you can adapt it to save it to a `.py` file if you wish to run it directly with `streamlit run`.

Also, make sure you have the `model.h5` file and `tensorflow` installed if you intend to run this code, as well as `Pillow` for image handling.
```
"""

import streamlit as st
import numpy as np
from PIL import Image


# Ensure the model file exists in your Colab environment or provide a full path
# If you're running this as a .py file, the model.h5 should be in the same directory
# If running directly in .ipynb, you might need to upload it or specify its path
try:
    model = tf.keras.models.load_model("model.h5")
except Exception as e:
    st.error(f"Error loading model.h5: {e}. Please ensure 'model.h5' is available in the expected path.")
    st.stop()

class_names = ["Non-Violence", "Violence"]

st.title("Violence Detection App")

uploaded_file = st.file_uploader("Upload Image", type=["jpg","png"])

if uploaded_file is not None:
    img = Image.open(uploaded_file)

    if img.mode != "RGB":
        img = img.convert("RGB")

    img = img.resize((224,224))
    img_array = np.array(img)
    img_array = np.expand_dims(img_array, axis=0)

    if 'model' in locals(): # Only try to predict if the model was loaded successfully
        prediction = model.predict(img_array)
        result = np.argmax(prediction)

        st.image(img)
        st.write("Prediction:", class_names[result])
    else:
        st.warning("Model was not loaded, cannot make predictions.")

